TrajectoryPlannerROS:

  holonomic_robot: false
  controller_frequency: 3.0
  
  meter_scoring: true
  pdist_scale: 0.8
  gdist_scaler: 0.8
  publish_cost_grid_pc: false
  sim_time: 2.0
  
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.10
  
  acc_lim_x: 5.0
  acc_lim_y: 5.0
  acc_lim_theta: 6.4
  
  controller_frequency: 10.0    # (double, default 20.0)
  oscillation_reset_dist: 0.1   # (double, default 0.05) How far the robot must travel in meters before oscillation flags are reset
  escape_vel: -0.4              # (double, default -0.1) Speed used for driving during escapes in meters/sec. Note that it must be negative in order for the robot to actually reverse.
  heading_scoring_timestep: 1.2 # (double, default: 0.8) How far to look ahead in time in seconds along the simulated trajectory when using heading scoring
