map_type: costmap

obstacle_range: 3.0
raytrace_range: 7.0

transform_tolerance: 1.0

robot_radius: 0.5
inflation_radius: 0.4

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /udacity_bot/laser/scan, marking: true, clearing: true}
