#
# Trajectory Planner local cost map parameters
#
local_costmap:
   global_frame: odom
   robot_base_frame: robot_footprint
   update_frequency: 10.0              # (double, default 5.0) The frequency in Hz for the map to be updated.
   publish_frequency: 10.0             # (double, default 0.0) The frequency in Hz for the map to be publish display information.
   width: 5.0                          # The width of the map in meters.(int, default 10) The width of the map in meters.
   height: 5.0                         # (int, default 10) The width of the map in meters.
   resolution: 0.05                     # (double, default 0.05) The resolution of the map in meters/cell.
   static_map: false
   rolling_window: true                 # Whether or not to use a rolling window version of the costmap. If the static_map parameter is set to true, this parameter must be set to false.